data_dir: data
results_dir: wav # output example ./data/IEMOCAP_mcadams/wav

pipeline: mcadams
anon_suffix: _mcadams

datasets:
  - name: stark
    data: stark

modules:
  anon_suffix: _mcadams
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  # anon_level_spk: [stark]
  anon_level_utt: [stark]